In [50]:
import pandas as pd

In [51]:
df = pd.read_csv("dictionnaire_de_reco_films.csv")

In [52]:
df

,Unnamed: 0,0
0,Kate & Leopold_2001,"[""It's a Boy Girl Thing_2006"", 'Woman on Top_2..."
1,The Other Side of the Wind_2018,"['Novitiate_2017', 'The Boys in the Band_2020'..."
2,Chinese Coffee_2000,"['Salomé_2013', 'The Panic in Needle Park_1971..."
3,The Dancer Upstairs_2002,"['Julia_2008', 'The Lost_2006', 'Enough_2002',..."
4,Don's Plum_2001,"['Sunset Strip_2000', 'Joe Somebody_2001', 'Be..."
...,...,...
14003,Le Procès du chien_2024,"['Alibi.com 2_2023', 'Chambre 212_2019', 'Tout..."
14004,Black Tea_2024,"[""Bang Gang (une histoire d'amour moderne)_201..."
14005,La promesse verte_2024,"['Le lycéen_2022', 'Saint Omer_2022', 'Retour ..."
14006,Une part manquante_2024,"['Nos batailles_2018', 'Serre moi fort_2021', ..."
14007,À toute allure_2024,"['Friendzone_2021', 'Épouse-moi mon pote_2017'..."

In [55]:
# Exemple : Renommer toutes les colonnes
df.columns = ["index", "recos"]

In [56]:
df

,index,recos
0,Kate & Leopold_2001,"[""It's a Boy Girl Thing_2006"", 'Woman on Top_2..."
1,The Other Side of the Wind_2018,"['Novitiate_2017', 'The Boys in the Band_2020'..."
2,Chinese Coffee_2000,"['Salomé_2013', 'The Panic in Needle Park_1971..."
3,The Dancer Upstairs_2002,"['Julia_2008', 'The Lost_2006', 'Enough_2002',..."
4,Don's Plum_2001,"['Sunset Strip_2000', 'Joe Somebody_2001', 'Be..."
...,...,...
14003,Le Procès du chien_2024,"['Alibi.com 2_2023', 'Chambre 212_2019', 'Tout..."
14004,Black Tea_2024,"[""Bang Gang (une histoire d'amour moderne)_201..."
14005,La promesse verte_2024,"['Le lycéen_2022', 'Saint Omer_2022', 'Retour ..."
14006,Une part manquante_2024,"['Nos batailles_2018', 'Serre moi fort_2021', ..."
14007,À toute allure_2024,"['Friendzone_2021', 'Épouse-moi mon pote_2017'..."

In [60]:
df.to_csv("dico_reco_2.csv", index=False)

In [58]:
df[df["index"] == "Spider-Man_2002"]

              index                                              recos
44  Spider-Man_2002  ['Spider-Man 2_2004', 'Spider-Man 3_2007', 'Bl...

In [65]:
dff = pd.read_csv("nettoyage_des_donnees_VF2.csv")
len(dff)

13941

In [64]:
df_enc = pd.read_csv("titles_encoded.csv")
len(df_enc)

13941

In [67]:
df_all = pd.concat([dff, df_enc], axis=1)
df_all

,tconst,primaryTitle,startYear,runtimeMinutes,genres,originalTitle,averageRating,numVotes,category,characters,...,original_language,overview,production_companies_name,production_companies_country,imdb_id_y,poster_path,nconst,index,originalTitle,encodedTitle
0,tt0035423,Kate & Leopold,2001,118,"Comedy,Fantasy,Romance",Kate & Leopold,6.4,91790.0,"['actor', 'actor', 'actor', 'actor', 'actor', ...","['[""Leopold""]', '[""Stuart Besser""]', '[""Charli...",...,en,When her scientist ex-boyfriend discovers a po...,"['Konrad Pictures', 'Miramax']","['', 'US']",tt0035423,https://image.tmdb.org/t/p/w500/mUvikzKJJSg9kh...,NaN,Kate & Leopold_2001,Kate & Leopold,Kate%20%26%20Leopold
1,tt0069049,The Other Side of the Wind,2018,122,Drama,The Other Side of the Wind,6.7,8303.0,"['actor', 'actor', 'actor', 'actor', 'actor', ...","['[""Jake Hannaford""]', '[""Brooks Otterlake""]',...",...,en,"Surrounded by fans and skeptics, grizzled dire...","['SACI', ""Les Films de l'Astrophore""]",NaN,tt0069049,https://image.tmdb.org/t/p/w500/kFky1paYEfHxfC...,NaN,The Other Side of the Wind_2018,The Other Side of the Wind,The%20Other%20Side%20of%20the%20Wind
2,tt0118852,Chinese Coffee,2000,99,Drama,Chinese Coffee,7.0,4850.0,"['actor', 'actor', 'actor', 'actor', 'actor', ...","['[""Harry Levine""]', '[""Jake Manheim""]', '[""Ma...",...,en,"When Harry Levine, an aging, unsuccessful Gree...","['Chal Productions', 'Shooting Gallery']",NaN,tt0118852,https://image.tmdb.org/t/p/w500/nZGWnSuf1FIuzy...,NaN,Chinese Coffee_2000,Chinese Coffee,Chinese%20Coffee
3,tt0118926,The Dancer Upstairs,2002,132,"Crime,Drama,Thriller",The Dancer Upstairs,6.8,7120.0,"['actor', 'actor', 'actor', 'actor', 'actor', ...","['[""Rejas""]', '[""Sucre""]', '[""Merino""]', '[""Ca...",...,en,A police detective in a South American country...,"['Vía Digital', 'Fox Searchlight Pictures', 'L...","['ES', 'US', 'ES', 'US', 'ES']",tt0118926,https://image.tmdb.org/t/p/w500/jG662jKzEf63fh...,NaN,The Dancer Upstairs_2002,The Dancer Upstairs,The%20Dancer%20Upstairs
4,tt0119004,Don's Plum,2001,89,"Comedy,Drama",Don's Plum,5.5,4908.0,"['actor', 'actor', 'actor', 'actor', 'actor', ...","['[""Brad""]', '[""Jeremy""]', '[""Ian""]', '[""Derek...",...,en,A group of Los Angeles teenagers meets daily a...,"['Polo Pictures Entertainment', 'Trust Film Sv...",NaN,tt0119004,https://image.tmdb.org/t/p/w500/6XGIqk8DDFtjyH...,NaN,Don's Plum_2001,Don's Plum,Don%27s%20Plum
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13936,tt0064791,Rider on the Rain,1970,115,"Crime,Drama,Mystery",Le passager de la pluie,6.6,4121.0,"['actor', 'actor', 'actor', 'actor', 'actor', ...","['[""Col. Harry Dobbs""]', '[""Tony Mau""]', '[""In...",...,fr,A US Army colonel in France tries to track dow...,"['Greenwich Film Production', 'Medusa Produzio...",NaN,tt0064791,https://image.tmdb.org/t/p/w500/ibS8mKviuPe7PK...,"['nm0000314', 'nm0864081', 'nm0310481', 'nm068...",Le passager de la pluie_1970,Le passager de la pluie,Le%20passager%20de%20la%20pluie
13937,tt0090206,Three Men and a Cradle,1985,106,Comedy,3 hommes et un couffin,6.6,4109.0,"['actor', 'actor', 'actor', 'actor', 'actor', ...","['[""Pierre""]', '[""Michel""]', '[""Jacques""]', '\...",...,fr,"Three young men (Jacques, Pierre and Michel) s...","['Soprofilms', 'TF1 Films Production', 'Flach ...","['', 'FR', 'FR']",tt0090206,https://image.tmdb.org/t/p/w500/3TfJL5jbyWFUOe...,"['nm0320801', 'nm0099378', 'nm0244707', 'nm002...",3 hommes et un couffin_1985,3 hommes et un couffin,3%20hommes%20et%20un%20couffin
13938,tt0069398,All's Well,1972,95,Drama,Tout va bien,6.5,4028.0,"['actor', 'actor', 'actor', 'actor', 'actor', ...","['[""Him, Jacques""]', '[""Factory Manager""]', '[...",...,fr,A strike at a French sausage factory contribut...,"['Anouchka Films', 'Vieco Films', 'Empire Films']","['FR', '', '']",tt0069398,https://image.tmdb.org/t/p/w500/o13al7oguvpSDe...,"['nm0598971', 'nm0135671', 'nm0144911', 'nm015...",Tout va bien_1972,Tout va bien,Tout%20va%20bien
13939,tt0082054,Beau-père,1981,123,"Comedy,Drama,Romance",Beau-père,6.9,4013.0,"['actor', 'actor', 'actor', 'actor', 'actor', ...","['[""Rémi Bachelier""]', '[""Charly""]', '[""Nicola...",...,fr,Rémi is a man trapped in a deteriorating marri...,"['Sara Films', 'Antenne 2']",NaN,tt0082054,https://image.tmdb.org/t/p/w500/hzGFiFY8wYeqxM...,"['nm0223033', 'nm0740067', 'nm0728208', 'nm049...",Beau-père_1981,Beau-père,Beau-p%C3%A8re
13940,tt26446278,The Count of Monte-Cristo,2024,178,"Action,Adventure,Drama",Le Comte de Monte-Cristo,7.6,35554.0,"['actor', 'actor', 'actor', 'actor', 'actor', ...","['[""Edmond Dantès""]', '[""Fernand de Morcef""]',...",...,fr,NaN,"['Chapter 2', 'Fargo Films', 'Pathé']","['FR', 'FR', 'FR']",tt26446278,https://image.tmdb.org/t/p/w500/41sfnbdRIw2dbp...,"['nm2582755', 'nm3319078', 'nm0480850', 'nm026...",Le Comte de Monte-Cristo_2024,Le Comte de Monte-Cristo,Le%20Comte%20de%20Monte-Cristo

In [68]:
df_all.to_csv("nettoyage_des_donnees_VF2.csv", index=False)